-- # DB schema
-- # TABLE transactions
-- # id (unique)
-- # amount
-- # account_no
-- # created_datetime
-- # type - CR/DB
-- # utr
-- #
-- # TABLE accounts
-- # id (unique)
-- # name
-- # balance
-- # account_no
-- # last_transaction
DROP TABLE IF EXISTS ACCOUNTS;
DROP TABLE IF EXISTS LEDGER;
DROP TABLE IF EXISTS TRANSACTIONS;

CREATE TABLE ACCOUNTS (
    ACCOUNTID int NOT NULL,
    NAME varchar(255),
    BALANCE int NOT NULL,
    LASTTRANSACTIONID int,
    PRIMARY KEY (ACCOUNTID),
    FOREIGN KEY (LASTTRANSACTIONID) REFERENCES LEDGER(UNIQUEID)
);

CREATE TABLE LEDGER (
    UNIQUEID INTEGER PRIMARY KEY AUTOINCREMENT,
    FROMTRANSID int NOT NULL,
    TOTRANSID int NOT NULL,
    STAMP varchar(255),
    FOREIGN KEY (FROMTRANSID) REFERENCES TRANSACTIONS(TRANSID)
    FOREIGN KEY (TOTRANSID) REFERENCES TRANSACTIONS(TRANSID)
);

CREATE TABLE TRANSACTIONS (
    TRANSID INTEGER PRIMARY KEY AUTOINCREMENT,
    ACCOUNTID int NOT NULL,
    AMOUNT int NOT NULL,
    TRANSACTIONTYPE varchar(255),
    FOREIGN KEY (ACCOUNTID) REFERENCES accounts(ACCOUNTID)
);